version: 2
jobs:
  build:
    resource_class: large
    docker:
      - image: continuumio/miniconda3:4.6.14
    steps:
      - checkout

      # Create conda env with all deps.
      - restore_cache:
          keys:
            - v2-conda-{{ checksum "env.yml" }}
      - run:
         command: |
          if [[ ! -d "/opt/conda/envs/phyre/" ]]; then
            conda env create -f env.yml
          fi
      - save_cache:
          key: v2-conda-{{ checksum "env.yml" }}
          paths: /opt/conda/envs/phyre/

      # Restore node cache.
      - restore_cache:
          keys:
            - v1-npm-{{ checksum "src/viz/package.json" }}-{{ checksum "src/viz/package-lock.json" }}

      # Install phyre.
      - run:
         command: |
           apt-get update
           apt-get install build-essential --yes
           conda init bash
           . ~/.bashrc
           conda activate phyre
           pip install -e src/python

      # Save node package cache.
      - save_cache:
          key: v1-npm-{{ checksum "src/viz/package.json" }}-{{ checksum "src/viz/package-lock.json" }}
          paths: src/viz/node_modules/

      # Run tests.
      - run:
         command: |
           . ~/.bashrc
           conda activate phyre
           make test
